version: 0.2

# run-as: Linux-user-name

phases:

  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Entered build phase"
  post_build:
    commands:
      - echo "Entered post-build phase"
artifacts:
  files:
    - '**/*'