# Generated by Django 2.1.7 on 2019-03-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillowID', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('legalDescription', models.CharField(max_length=100)),
                ('livingSF', models.IntegerField()),
                ('landSF', models.IntegerField()),
                ('yearBuilt', models.IntegerField()),
                ('age', models.IntegerField()),
                ('ownerName', models.CharField(max_length=100)),
                ('homeStead', models.CharField(max_length=50)),
                ('subjectToNotIncludedInSale', models.IntegerField()),
                ('taxesCoveredInSuit', models.IntegerField()),
                ('totalTaxesOwed', models.IntegerField()),
                ('valuesAdjudged', models.IntegerField()),
                ('valuesLandCAD', models.IntegerField()),
                ('valuesBldgCAD', models.IntegerField()),
                ('valuesCAD', models.IntegerField()),
                ('StartingBid', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
