# Generated by Django 2.1.7 on 2019-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_zestimate'),
    ]

